//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WA.WcfClient.WcfServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfServiceReference.IWcfService")]
    public interface IWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/GetAvailableCitiesForTomorrow", ReplyAction="http://tempuri.org/IWcfService/GetAvailableCitiesForTomorrowResponse")]
        System.Collections.Generic.List<string> GetAvailableCitiesForTomorrow(System.DateTime today);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/GetAvailableCitiesForTomorrow", ReplyAction="http://tempuri.org/IWcfService/GetAvailableCitiesForTomorrowResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetAvailableCitiesForTomorrowAsync(System.DateTime today);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/GetWeatherInfo", ReplyAction="http://tempuri.org/IWcfService/GetWeatherInfoResponse")]
        WA.Common.WeatherGrabber.WeatherInfo GetWeatherInfo(string cityName, System.DateTime today);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/GetWeatherInfo", ReplyAction="http://tempuri.org/IWcfService/GetWeatherInfoResponse")]
        System.Threading.Tasks.Task<WA.Common.WeatherGrabber.WeatherInfo> GetWeatherInfoAsync(string cityName, System.DateTime today);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfServiceChannel : WA.WcfClient.WcfServiceReference.IWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfServiceClient : System.ServiceModel.ClientBase<WA.WcfClient.WcfServiceReference.IWcfService>, WA.WcfClient.WcfServiceReference.IWcfService {
        
        public WcfServiceClient() {
        }
        
        public WcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<string> GetAvailableCitiesForTomorrow(System.DateTime today) {
            return base.Channel.GetAvailableCitiesForTomorrow(today);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<string>> GetAvailableCitiesForTomorrowAsync(System.DateTime today) {
            return base.Channel.GetAvailableCitiesForTomorrowAsync(today);
        }
        
        public WA.Common.WeatherGrabber.WeatherInfo GetWeatherInfo(string cityName, System.DateTime today) {
            return base.Channel.GetWeatherInfo(cityName, today);
        }
        
        public System.Threading.Tasks.Task<WA.Common.WeatherGrabber.WeatherInfo> GetWeatherInfoAsync(string cityName, System.DateTime today) {
            return base.Channel.GetWeatherInfoAsync(cityName, today);
        }
    }
}
